collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.01918927510268986
color:
  saturation: 0.8481009411625564
  brandStrength: 0.8976175731513649
  rhythmicContrast: 0.4893655302003026
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.9771308617200702
layout_spectrum: 0.4175627
name: www.maneantu.com
